### ISSUE TITLE
Portal Page: Add user Management for per Seat Users

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#135] opened 2021-09-29 20:51 UTC
**Is your feature request related to a problem? Please describe.**
Add a Portal section to manage the user licenses (M365 and Teams)

**Describe the solution you'd like**
Allow buyers to manage their users consuming their seats

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaelSchreiber** [comment] 2022-08-03 08:22
Feature request: I also need a way to assign licenses to users for per-seat based offers.
Though this could be done within the application, a solution is required in case the number of seats is reduced.
E.g., if 10 users are assigned licenses and the number of licenses is decreased to 5. Which users would loose their license?
A possible solution would be to mark all licenses as unused and on a first comes first served principle assign licenses to users when they login and mark them as used up to the number of licenses purchased.
Users must be identified by their object id (not their email) to cover the case when the user changes his logon email address.

**Comment by santhoshb-msft** [comment] 2022-12-06 05:08
@code4clouds is this a duplicate of #130 ? Closing this for now, please reopen if not.

**Closed by santhoshb-msft** 2022-12-06 05:08 UTC
