### ISSUE TITLE
Add configurable endpoint to send notifications about saas subscriptions changes to external solution

### ISSUE THREAD

**Issue by olsoro0** [Azure/Commercial-Marketplace-SaaS-Accelerator#251] opened 2022-05-24 20:32 UTC
**Is your feature request related to a problem? Please describe.**
Several publishers requested saas subscription changes notifications to be sent to their solution.

**Describe the solution you'd like**
Add configurable endpoint URL to application config, so that it can be edited in the admin page. Notifications for saas subscription changes will be sent to this URL through a proxy call. The feature can be activated in admin Plans page (see the image below).

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/97641588/170125605-c8572734-5945-45eb-90c6-27b4c47530b3.png)

**Comment by dstarr** [comment] 2022-12-04 18:36
Duplicate of https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/issues/274

**Comment by santhoshb-msft** [comment] 2023-09-25 21:37
Covered in #534 #close

**Closed** 2023-09-25 21:37 UTC
Labels: duplicate, enhancement
