### ISSUE TITLE
Add an admin page to update logos

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#146] opened 2021-10-29 16:35 UTC
**Is your feature request related to a problem? Please describe.**
As a Publisher,
I would like to have an admin page to change logo,
So, I don't need my dev team to change it

**Describe the solution you'd like**
A page on the admin section to upload the new logo (.png and .ico).

**Describe alternatives you've considered**

**Additional context**

**Comment by olsoro0** [comment] 2022-03-28 22:30
This is a duplicate of #[203](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/issues/203)

**Closed by olsoro0** 2022-03-28 22:30 UTC
Labels: enhancement
