### ISSUE TITLE
Send payload to a custom webhook to automate SaaS workflow

### ISSUE THREAD

**Issue by clementchane** [Azure/Commercial-Marketplace-SaaS-Accelerator#477] opened 2023-04-20 04:42 UTC
Hello!

**Is your feature request related to a problem? Please describe.**
I need to send my payload to an external webhook to trigger the creation of the account in our SaaS application.
Currently I have a script running on an Azure automation account that retrieves a webhook data and use it to create an account in our SaaS environment.

**Describe the solution you'd like**
When clicking on the "Activate" button on the customer portal, the payload should be sent to a custom webhook in addition to what is already existing. 
This webhook URL should be configurable in the admin portal.

**Describe alternatives you've considered**
None, but I am open to suggestions on how to trigger a workflow when the customer click on the "activate" button.

**Additional context**
This is a feature provided by 3rd party companies providing the marketplace landing page, but we would like to create our own page.

**Comment by santhoshb-msft** [comment] 2023-04-26 16:59
Duplicate of #134

**Comment by santhoshb-msft** [comment] 2023-04-26 17:00
Hi @clementchane - thank you for raising this issue. We will track it at #134

**Closed by santhoshb-msft** 2023-04-26 17:00 UTC
