### ISSUE TITLE
Configure account results in 500 string was not recognized as valid boolean

### ISSUE THREAD

**Issue by git657** [Azure/Commercial-Marketplace-SaaS-Accelerator#503] opened 2023-05-24 17:18 UTC
**To Reproduce**
subscribe to an offer.
click configure account
fill out subscription details and subscribe
result:
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/109476070/b1354deb-d666-4c31-b10a-a62cf63a5ac1)

tho the user is actually subscribed

**Expected behavior**
return to the landing page

**Screenshots**

**Environment (please complete the following information):**
 - Are you using the CloudShell?
 - yes
 - If not using the CloudShell:
    - PowerShell version
    - Modules installed
    
**Additional context**

**Comment by santhoshb-msft** [comment] 2023-05-25 00:01
Hi @hemmy13 this could be specific to your config. Could you please review the config information?

**Comment by hemmy13** [comment] 2023-05-26 10:55
hi @santhoshb-msft my config is the same as what is in this repo

**Comment by git657** [comment] 2023-05-26 10:59
Also @santhoshb-msft the configuration is successful, if I go back to the home page, but everytime I am first directed to this error page

**Comment by git657** [comment] 2023-05-26 11:10
@santhoshb-msft  
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/109476070/cd79ac79-1425-4a8c-87bf-868e0552cfcd)

**Comment by santhoshb-msft** [comment] 2023-08-08 22:29
Hi @git657 
There seem to some mis configuration in your environment, I recommend locally debugging to get to the root cause of this issue.

**Comment by santhoshb-msft** [comment] 2023-09-25 19:55
Hi @git567 I hope you were able to resolve this. Please let us know if you were able to repro this. Closing this for now, but please reopen with some repro steps so we can work towards a resolution if there is any issues. Thank you!

**Closed by santhoshb-msft** 2023-09-25 19:55 UTC
Labels: triage
