### ISSUE TITLE
Could not find file '/home/USER/Commercial-Marketplace-SaaS-Accelerator/deployment/script.sql'.

### ISSUE THREAD

**Issue by msmassimo** [Azure/Commercial-Marketplace-SaaS-Accelerator#575] opened 2023-10-17 16:33 UTC
**To Reproduce**
1. Run Deploy Script 

OUTPUT - CANNOT PROCEED
➡️ Execute SQL schema/data script Invoke-Sqlcmd: /home/USER/Commercial-Marketplace-SaaS-Accelerator/deployment/Deploy.ps1:347 Line |  347 |  Invoke-Sqlcmd -InputFile ./script.sql -ServerInstance $ServerUri -dat …      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      | Could not find file '/home/USER/Commercial-Marketplace-SaaS-Accelerator/deployment/script.sql'.

**Comment by santhoshb-msft** [comment] 2023-10-17 16:49
Hi @msmassimo this most likely means the build didnt succeed. Did you run the complete deployment script which install dotnet 6?

**Comment by msmassimo** [comment] 2023-10-18 08:13
Correct. 

However, according to the instllation guide the command:

dotnet tool install --global dotnet-ef; 

will install 7.0

Used: 
dotnet tool install --global dotnet-ef --version 6.0.0
 
and it now works.

**Comment by santhoshb-msft** [comment] 2023-10-18 16:42
@msmassimo I dont think the error is caused by the dotnet-ef version. It might be the dotnet version itself. I just ran with dotnet-ef 7 and build works fine, 
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/63607175/d8490711-64d8-4425-a428-755e907f9492)

But yes we need to run the first 4 lines of installation script to have dotnet 6.0 installed. Closing this as no further changes needed, please feel free to reopen with additional info.

**Closed by santhoshb-msft** 2023-10-18 16:42 UTC
