### ISSUE TITLE
Forbidden: Client is not authorized for this usage resource

### ISSUE THREAD

**Issue by lostmsu** [Azure/Commercial-Marketplace-SaaS-Accelerator#103] opened 2020-08-28 01:24 UTC
**Describe the bug**
Reporting metered usage in batch fails with 

> HTTP 403: Forbidden. Client is not authorized for this usage resource.

for each dimension.

This happens on a private plan, that was created and subscribed to recently (the previous plan has been unsubscribed and stopped selling).

**Comment by santhoshb-msft** [comment] 2020-08-28 02:18
This bug might not be an application bug rather Marketplace API bug. Try with postman and if still persists could you please create a ticket at
https://partner.microsoft.com/en-US/dashboard/support/isv/servicerequests/create?stage=1

![image](https://user-images.githubusercontent.com/63607175/91513650-b6a30a00-e899-11ea-83ed-6bb6ed01f495.png)

**Comment by santhoshb-msft** [comment] 2022-03-15 05:52
@lostmsu , I hope the issue is fixed, please reopen if not.
Closing this for now.

**Closed by santhoshb-msft** 2022-03-15 05:52 UTC
